# Generated by Django 3.2.16 on 2022-11-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='Muallif nomi')),
                ('title', models.CharField(max_length=255, verbose_name='Maqola nomi')),
                ('text', models.TextField(verbose_name='Maqola matni')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='vaqt')),
            ],
        ),
    ]
