# Generated by Django 3.2.16 on 2022-11-26 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Darajasi')),
                ('unvoni', models.CharField(choices=[('Y', 'bor'), ('NO', 'yoq'), ('Z', '----')], default='Z', max_length=10, verbose_name='Unvoni')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Isim')),
                ('l_name', models.CharField(max_length=100, verbose_name='Falmilya')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyiha1.position')),
            ],
        ),
    ]
